# Generated by Django 5.1 on 2024-08-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_review_ratings_remove_book_avarage_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book_rating',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
