# Generated by Django 5.1 on 2024-08-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_review_book_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ratings',
        ),
    ]
