# Generated by Django 5.1 on 2024-08-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_review_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='number_of_comments',
            field=models.IntegerField(default=0),
        ),
    ]
