# Generated by Django 5.1 on 2024-08-28 09:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_review_comment_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review_comments',
            new_name='ReviewComment',
        ),
        migrations.RenameModel(
            old_name='Review_comment_likes',
            new_name='ReviewCommentLike',
        ),
        migrations.RenameModel(
            old_name='Review_likes',
            new_name='ReviewLike',
        ),
        migrations.RenameField(
            model_name='reviewcommentlike',
            old_name='review_comment_likes',
            new_name='review_comment',
        ),
        migrations.AlterUniqueTogether(
            name='reviewcommentlike',
            unique_together={('review_comment', 'user')},
        ),
    ]
